name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload to Pinata
        uses: ipfs-shipyard/ipfs-deploy@v0.3.1
        with:
          apiKey: ${{ secrets.PINATA_API_KEY }}
          apiSecret: ${{ secrets.PINATA_API_SECRET }}
          sourcePath: .  # Upload all files from the repository
