name: Deploy to IPFS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload to Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pin-name: 'My personal site'
          path: './build'
          pinata-api-key: b2ef103c3746a03df375
          pinata-secret-api-key: b79749f540fd01bd2874c4d8280f38002147a1b4382c77acc777ba99ede0e420
          verbose: true
          remove-old: false
